import { GoogleAnalytics } from '@next/third-parties/google'
import type { Metadata } from 'next'
import Header from '@/components/layouts/header'
import localFont from 'next/font/local'
import Providers from '@/providers'
import '@rainbow-me/rainbowkit/styles.css'
import './globals.css'
import TopLoader from '@/components/top-loader.tsx'
import { AOSInit } from '@/components/aos'

const myFont = localFont({
  src: [
    {
      path: './fonts/IBMPlexMono-Bold.ttf',
      weight: '700'
    },
    {
      path: './fonts/IBMPlexMono-ExtraLight.ttf',
      weight: '200'
    },
    {
      path: './fonts/IBMPlexMono-Light.ttf',
      weight: '300'
    },
    {
      path: './fonts/IBMPlexMono-Medium.ttf',
      weight: '500'
    },
    {
      path: './fonts/IBMPlexMono-Regular.ttf',
      weight: '400'
    },
    {
      path: './fonts/IBMPlexMono-SemiBold.ttf',
      weight: '600'
    },
    {
      path: './fonts/IBMPlexMono-Thin.ttf',
      weight: '100'
    }
  ],
  display: 'swap',
  variable: '--font-ibm-plex-mono'
})

export const metadata: Metadata = {
  title: '0xpenGuildWTF',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${myFont.className} ${myFont.variable} custom-selection antialiased`}>
        <Providers>
          <AOSInit />
          <TopLoader />
          <Header />
          <main className='flex flex-col gap-2 pt-[120px]'>{children}</main>
        </Providers>
      </body>
      <GoogleAnalytics gaId='G-QNXHRV4MHW' />
    </html>
  )
}
